### ISSUE TITLE
Drobné korekce

### ISSUE THREAD

**Issue by JakubVanek** [basta/PRG_Questions#1]
Ahoj,

díky za tenhle materiál! Zkusil jsem to projít, napadlo mě pár vylepšení (čísla otázek jsou vůči markdownu):

 * 1653493561571 - technicky vzato můžou být i v registrech, ale je to závislé na architektuře procesoru a systému; ale tohle se IIRC v PRG neučí
 * ~~1653493561575 - řekl bych, že spíše ne. C++ na dyn. alokací má přímo klíčové slovo `new`, C na to má jenom `malloc()` ve standardní knihovně, která není klíčovým slovem~~
 * 1653493561594 - záleží na verzi jazyka: v C89 neexistuje bool typ, existuje opravdu jenom int apod. V C99 existuje vestavěný typ `_Bool`, který se dá typedef-nout na `bool` a jsou pro něj určené právě `true`/`false` ze `<stdbool.h>`
 * 1653493561612 - complement by měl být `~`, `-` je dvojkový doplněk/mínusování čísla
 * 1653495873270 - zde bych do scanf přidal omezení na délku řetězce (`%255s`), jinak hrozí přetečení, ale to `%s` asi budou brát taky
 * 1653780185943 - tady existuje zlepšovák - přímo `%p`
 * `Jak probíhá proces spuštění programu implementovaného v jazyce C?` - napadá mě tohle, ale může to být ještě jinak
    1. jádro (nebo jiný zavaděč) kód a data programu nakopírují do RAM
    2. jádro vytvoří nový proces (pouze v případě OS)
    3. (volitelné, pouze pod OS) zavolá se linker, pokud jde o dynamicky linkovaný program. Ten najde chybějící funkce ve sdílených knihovnách, načte je do to paměti a doplní do programu odkazy na funkce. V praxi se to ještě mírně liší - kvůli rychlejšímu startu programu se část funkcí hledá až při jejich prvním zavolání. První zavolání je přesměrované na linker, druhé a další už volá přímo danou funkci.
    4. jádro uvnitř procesu (nebo zavaděč) skočí do inicializační procedury Cčkové knihovny, ta provede další inicializační kroky (příprava zásobníku, inicializace dat, ...)
    5. Cčková knihovna skočí do `main()`
 * `Jaký význam má klíčové slovo static v závislosti na kontextu?` - ještě je tam jedna obskurnost - dá se použít v deklaraci funkce při předávání pole - https://hamberg.no/erlend/posts/2013-02-18-static-array-indices.html
 * 1653780185964 - `int eye[3][3] = { [0][0] = 1, [1][1] = 1, [2][2] = 1 };`
 * 1653780185977 - jsou tam jenom přehozené typy a názvy proměnných
 * 1653780186040 - snad jo, `fseek()` se mi zdá rozumný
 * 1653780186041 - tady bych spíš použil `fread()`/`fwrite()`, `read()`/`write()` jsou POSIXová systémová volání
 * 1653780186046 - vlastně duplikát 1653780186064

Jsou to ale jenom detaily, celkově se mi to zdá solidní.

S pozdravem

Kuba

**Comment by basta** [comment]
- Otázku `Jak probíhá proces spuštění programu implementovaného v jazyce C?` jsem od tebe zkopíroval, protože bych to nikdy líp nenapsal. 

- O tomhle využití static jsem neměl ani ponětí, přidám to tam. Je to zajímavá obskurita, která by udělala fajglovi radost

- U `1653780185964` zkopíruju tvůj snippet a dám ho tam, očividně mi nějak zamrzl mozek. 

Vlastně se vším, co jsi psal jsem souhlasil a zapracoval jsem to. 

Díky moc za detailní korekturu, přesně v něco takovýho jsem doufal, když jsem to psal a dával na github. 

Ještě jednou dík,
Ondra
